name: Update Dependencies

on:
  schedule:
    - cron: '0 0 * * 1' # Schedule to run weekly on Mondays
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Update ws dependency
      run: npm update ws --legacy-peer-deps

    - name: Update ip dependency
      run: npm update ip --legacy-peer-deps

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add package.json package-lock.json
        git commit -m "Update ws and ip to fix security vulnerabilities"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
